image: Visual Studio 2017
configuration: Release
platform: Any CPU
  
install:
- ps: $env:build_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version 
- ps: Update-AppveyorBuild -Version "$env:build_version.$env:APPVEYOR_BUILD_NUMBER"
- git submodule update --init

dotnet_csproj:
  patch: false
  file: '**\*.csproj'
  version: $(build_version)
  package_version: $(build_version)
#  file_version: $(APPVEYOR_BUILD_VERSION)

before_build:
- cmd: dotnet restore --verbosity q

build:
  project: package.sln
  parallel: true
  verbosity: minimal

after_build:
- cmd: del lib\*.nupkg
- cmd: NuGet pack

test_script:
- cmd: dotnet test --framework net47 --verbosity q

artifacts:
- path: '**\Unity.*.nupkg'
  name: 'Unity'

#deploy:
#- provider: GitHub
#  force_update: true
#  tag: $(appveyor_repo_tag_name)
#  release: v$(appveyor_build_version)
#  auth_token:
#    secure: 0RltkfAMN35pApf7xYqjwy1EgsVeniSYPv35Qb9ntHY1b4SC51QYLXVVfklvw09j
#  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
#  draft: false
#  prerelease: false
#  on:
#    appveyor_repo_tag: true        # deploy on tag push only  
#- provider: NuGet
#  api_key:
#    secure: Q/HUObjarHxWF0NlnHBDY5uMQHM4ESyKfFCYdbRVfsNrWUFozADu6FMvh44gEmFk
#  skip_symbols: false
#  artifact: /.*\.nupkg/
#  on:
#    appveyor_repo_tag: true        # deploy on tag push only  
