image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - ps: $env:build_version = (Select-Xml -Path ".\Package.nuspec" -XPath "/package/metadata/version" | Select-Object -ExpandProperty Node).InnerText
  - ps: Update-AppveyorBuild -Version "$env:build_version.$env:APPVEYOR_BUILD_NUMBER"
  - cmd: git submodule --quiet update --init

dotnet_csproj:
  patch: false

before_build:
- cmd: dotnet restore --verbosity q

build:
  project: package.sln
  parallel: true
  verbosity: quiet

after_build:
- cmd: del lib\*.nupkg
- cmd: NuGet pack -NoPackageAnalysis

before_test:
- choco install opencover.portable
- choco install codecov
  
test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test --framework net47 --verbosity q"

after_test:
- codecov -f "results.xml" 

# Disable artifacts for now
#artifacts:
#- path: 'Unity.*.nupkg'
#  name: 'Unity'
  
